### ISSUE TITLE
Environ try to read file witch not exists

### ISSUE THREAD

**Issue by MrMario108** [Dashboard-Manager/job-schedule#50]
In backend/config/dev.py line 11 environ try to read "docker.env". That file not exists. Probably it should be "django.env"

**Comment by radthenone** [comment]
https://github.com/Dashboard-Manager/job-schedule/blob/d892fc959fb00c99f24a35501aec4ae46a9cecd8/backend/config/settings/dev.py#L11
to
```py
environ.Env.read_env(os.path.join(ENV_DIR, "django.env")) 
```

ok, thanks for issue i correct this with my branch, and then add this to main orgin branch

**Comment by radthenone** [comment]
Done
